---
title: "Group Presentation Data Analysis"
author: "Group C"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data loading

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(echarts4r)

# Bring in the CSV data for earlier years
data_2015 <- readr::read_csv(here::here("source_data", "2015.csv"))
data_2016 <- readr::read_csv(here::here("source_data", "2016.csv"))
data_2017 <- readr::read_csv(here::here("source_data", "2017.csv"))
data_2018 <- readr::read_csv(here::here("source_data", "2018.csv"), na = c("", "N/A"))

# Bring in the Excel data for later years
data_2019 <- readxl::read_xlsx(here::here("source_data", "2019.xlsx"))
data_2021 <- readxl::read_xlsx(here::here("source_data", "2021.xlsx"))
```

Merge the data together, in a quick-and-dirty way, to figure out what will come in cleanly:

```{r}
data_2015 <- data_2015 |> dplyr::mutate(
  year = 2015
)

data_2016 <- data_2016 |> dplyr::mutate(
  year = 2016
)

data_2017 <- data_2017 |> dplyr::mutate(
  year = 2017
)

data_2018 <- data_2018 |> dplyr::mutate(
  year = 2018
)


data_2019 <- data_2019 |> dplyr::mutate(
  year = 2019
)

data_2021 <- data_2021 |> dplyr::mutate(
  year = 2021
)

data_joined <-
  dplyr::bind_rows(
    data_2015,
    data_2016,
    data_2017,
    data_2018,
    data_2019,
    data_2021
  )
```
